apiVersion: v1
kind: Service
metadata:
  name: robot
  namespace: default
spec:
  type: NodePort
  selector:
    app: robot
  ports:
    - name: robot
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 5672

apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: default
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - name: gateway
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 5672

apiVersion: v1
kind: Service
metadata:
  name: request
  namespace: default
spec:
  type: NodePort
  selector:
    app: request
  ports:
    - name: request
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 5672

